### PR TITLE
Secure HTML entities within template text

### PR DESCRIPTION
**Pull request by buihoanghai**
Fixes https://github.com/ampproject/amp-toolbox-php/issues/53

### CODE REVIEW

**Comment by westonruter** [comment]
It doesn't make sense to me why this would work. The `nodeValue` should contain the parsed HTML form. Also, `nodeValue` is supposed to be the same as `textContent`: https://www.php.net/manual/en/class.domnode.php#domnode.props.nodevalue

Nevertheless, it behaves differently: https://3v4l.org/qr5AD

```php
<?php
$dom = new DOMDocument();
$dom->loadHTML( '<!DOCTYPE html><html></html>' );

$tests = [
	'nodeValueUnescaped'   => [ 'nodeValue', 'http://example.com/?foo&bar' ],
	'textContentUnescaped' => [ 'textContent', 'http://example.com/?foo&bar' ],
	'nodeValueEscaped'     => [ 'nodeValue', 'http://example.com/?foo&amp;bar' ],
	'textContentEscaped'   => [ 'textContent', 'http://example.com/?foo&amp;bar' ],
];

foreach ( $tests as $i => list( $prop, $value ) ) {
	$dom->documentElement->appendChild( $dom->createTextNode( "\n" ) );
	$el = $dom->createElement( 'a' );
	$el->setAttribute( 'id', $i );

	$attr = $dom->createAttribute( 'href' );
	$attr->$prop = $value;
	$el->setAttributeNode( $attr );

	$dom->documentElement->appendChild( $el );
}
$dom->documentElement->appendChild( $dom->createTextNode( "\n" ) );

echo $dom->saveHTML();
```

There are also different results in PHP 5.6.1-5.6.13 versus all other versions:

> image

Compare this to the equivalent logic in JS (with same output in Chrome and Firefox): https://codepen.io/westonruter/pen/RwGXyNE

> image

This is what I expected to see from PHP, where the `nodeValue` and `textContent` behave identically, and also where any value supplied for the property is not parsed in any way.

It seems libxml in PHP is behaving very differently than the DOM spec requires.

**Comment by schlessera** [comment]
@buihoanghai The two test failures are unrelated and should be fixed in latest `main` branch. Can you please rebase this PR to latest `main` branch?

**Comment by schlessera** [comment]
@buihoanghai As you can see from the test I added, the simple use of `htmlspecialchars()` here is not a complete fix, as we are already losing some of the information at an earlier transformation, and thus an already encoded entity is erroneously reduced as well. I'll have to investigate further.

**Comment by schlessera** [comment]
@buihoanghai I've replaced the `htmlspecialchars` with a different approach that seems to keep the state of HTML entities in the exact form they were introduced, So `&` is preserved just as well as `&amp;`.

Can you test whether this fixes your specific issue and doesn't introduce a new problem?

@westonruter Thoughts on this approach?

**Comment by westonruter** [comment]
This doesn't seem to work quite right. Consider this:

```php
<?php

$html = '<template type="amp-mustache">
    <a data-href="https://example.com/?foo={{foo}}&bar={{bar}}&amp;baz={{baz}}">Link</a>
</template></html>';

$doc = new \AmpProject\Dom\Document();
$doc->loadHTML( $html );

echo $doc->saveHTML();
```

Notice how there the `&` and `&amp;` is inside of an `data-href` attribute and not `href` here. The output here is:

```html
<!DOCTYPE html>
<html><head><meta charset="utf-8"></head><body><template type="amp-mustache">
    <a data-href="https://example.com/?foo={{foo}}&amp;bar={{bar}}&amp;amp;baz={{baz}}">Link</a>
</template></body></html>
```

Notice the `&amp;` is getting serialized as `&amp;amp;` which is not correct.

I'm going to dig deeper.

**Comment by westonruter** [comment]
@schlessera I found that if the issue only occurs if updating an attribute value via `$attr->nodeValue`. It doesn't happen when updating an attribute value via `$el->setAttribute()`. Example code:

```php
$dom = new DOMDocument();
$dom->loadHTML( '<!DOCTYPE html><html data-test1="" data-test2=""></html>' );
$dom->documentElement->setAttribute( 'data-test1', 'foo&bar' );
$dom->documentElement->getAttributeNode( 'data-test2' )->nodeValue = 'foo&bar';
echo $dom->saveHTML();
```

Output:

```
Warning: main(): unterminated entity reference             bar in /in/UTRPQ on line 6
<!DOCTYPE html>
<html data-test1="foo&amp;bar" data-test2></html>
```

So I've updated the logic to do so. I've also made it only update the value if a replacement was actually made.

**Review by westonruter — APPROVED** [review]

**Comment by schlessera** [comment]
LGTM. @buihoanghai Can you test whether this latest incarnation solves your particular issue?

**Pull request merged**
