### PR TITLE
Fix AmpBoilerplateErrorHandler test

### PR DESCRIPTION
**Pull request by westonruter**
Fixes tests after #215.

### CODE REVIEW

**Comment by westonruter** [comment]
Er, actually this will just get overridden again.

**Comment by westonruter** [comment]
I suppose this is blocked by https://github.com/ampproject/amp-toolbox/pull/1236.

**Comment by schlessera** [comment]
Yes, the tests cannot be modified manually. In such a case, you'll need to add that test to the list of tests to skip: https://github.com/ampproject/amp-toolbox-php/blob/0.5.2/tests/Optimizer/SpecTest.php#L36-L46

I'll do that to get the tests to unfail. ;)

**Comment by schlessera** [comment]
See https://github.com/ampproject/amp-toolbox-php/pull/229/files

**Pull request closed without merging**
